### PR TITLE
chore: enhance TravisCI config

### PR DESCRIPTION
**Pull request by szepeviktor**
1. be explicit
1. in chronological order
1. uniform formatting

https://github.com/szepeviktor/emoji-picker-element/blob/patch-1/.travis.yml

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

kép

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by nolanlawson** [comment]
Cool, thanks! TIL `sudo: false` is deprecated. https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
